#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

if test -z "$NEWSGATE_DBDIR"; then
  echo "NEWSGATE_DBDIR envirinment variable not specified"
  exit
fi

mkdir -p "$NEWSGATE_DBDIR"

echo "Initializing MySQL data directory at $NEWSGATE_DBDIR"
mysql_install_db --user= --datadir=$NEWSGATE_DBDIR
