#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

mysql --port=$MYSQL_PORT --socket="$MYSQL_WORKSPACE_ROOT/mysql.socket" $@
