<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="<? loc PAGE_DESC ?>">
<title><? loc PAGE_TITLE ?> - <? conf server_instance_name ?></title>
<link rel="stylesheet" type="text/css" href="/fixed/css/help/search.css" media="all" />
</head>
<body>

<div id="topbar">

    <table>
    <tr><td id="page_name"><? loc PAGE_NAME ?> </td>
    <td id="right_menu"><a href="/"><? loc NEW_SEARCH ?></a></td>
    </tr>
    </table>

</div>

<!-- <div id="main_area" align="center"> -->
<table id="main_area" align="center">
<tr><td id="help_area">

<div class="op_group_heading"><? loc OVERVIEW_HEADING ?></div>
<div class="op_group_intro"><? loc OVERVIEW_INTRO ?></div>

<div class="op_group_heading"><a name="BASE_OPS"></a><? loc BASE_OPERATORS_HEADING ?></div>
<div class="op_group_intro"><? loc BASE_OPERATORS_INTRO ?></div>

<div class="op_desc"><a name="ALL"></a><? loc ALL_SEARCH ?></div>
<div class="sample_header"><? loc ALL_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc ALL_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="ANY"></a><? loc ANY_SEARCH ?></div>
<div class="sample_header"><? loc ANY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc ANY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="CATEGORY"></a><? loc CATEGORY_SEARCH ?></div>
<div class="sample_header"><? loc CATEGORY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc CATEGORY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="EVERY"></a><? loc EVERY_SEARCH ?></div>
<div class="sample_header"><? loc EVERY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc EVERY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="SITE"></a><? loc SITE_SEARCH ?></div>
<div class="sample_header"><? loc SITE_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc SITE_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="URL"></a><? loc URL_SEARCH ?></div>
<div class="sample_header"><? loc URL_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc URL_SEARCH_SAMPLES ?></div>

<div class="op_group_heading"><a name="LOGIC_OPS"></a><? loc LOGIC_OPERATORS_HEADING ?></div>
<div class="op_group_intro"><? loc LOGIC_OPERATORS_INTRO ?></div>

<div class="op_desc"><a name="AND"></a><? loc AND_SEARCH ?></div>
<div class="sample_header"><? loc AND_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc AND_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="EXCEPT"></a><? loc EXCEPT_SEARCH ?></div>
<div class="sample_header"><? loc EXCEPT_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc EXCEPT_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="OR"></a><? loc OR_SEARCH ?></div>
<div class="sample_header"><? loc OR_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc OR_SEARCH_SAMPLES ?></div>
<div class="op_precedence"><? loc LOGIC_OPERATORS_PRECEDENCE ?></div>

<div class="op_group_heading"><a name="RESTRICTING_OPS"></a><? loc RESTRICTING_OPERATORS_HEADING ?></div>
<div class="op_group_intro"><? loc RESTRICTING_OPERATORS_INTRO ?></div>

<div class="op_desc"><a name="CAPACITY"></a><? loc CAPACITY_SEARCH ?></div>
<div class="sample_header"><? loc CAPACITY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc CAPACITY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="COUNTRY"></a><? loc COUNTRY_SEARCH ?></div>
<div class="sample_header"><? loc COUNTRY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc COUNTRY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="DATE"></a><? loc DATE_SEARCH ?></div>
<div class="sample_header"><? loc DATE_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc DATE_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="DOMAIN"></a><? loc DOMAIN_SEARCH ?></div>
<div class="sample_header"><? loc DOMAIN_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc DOMAIN_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="FETCHED"></a><? loc FETCHED_SEARCH ?></div>
<div class="sample_header"><? loc FETCHED_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc FETCHED_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="LANGUAGE"></a><? loc LANG_SEARCH ?></div>
<div class="sample_header"><? loc LANG_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc LANG_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="VISITED"></a><? loc VISITED_SEARCH ?></div>
<div class="sample_header"><? loc VISITED_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc VISITED_SEARCH_SAMPLES ?></div>
<div class="op_desc"><a name="WITH"></a><? loc WITH_SEARCH ?></div>
<div class="sample_header"><? loc WITH_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc WITH_SEARCH_SAMPLES ?></div>

<div class="op_group_heading"><a name="TIME"></a><? loc TIME_HEADING ?></div>
<div class="op_group_intro"><? loc TIME_DESC ?></div>
<div class="sample_header"><? loc TIME_1 ?></div>
<div class="samples"><? loc TIME_1_SAMPLE ?></div>
<div class="sample_header"><? loc TIME_2 ?></div>
<div class="samples"><? loc TIME_2_SAMPLE ?></div>
<div class="sample_header"><? loc TIME_3 ?></div>
<div class="samples"><? loc TIME_3_SAMPLE ?></div>

<!-- </div> -->
</td>
<td id="right_bar">
<div class="right_bar_title"><a href="#BASE_OPS"><? loc BASE_OPERATORS_HEADING ?></div>
<div class="right_bar_item">
<a href="#ALL">ALL</a>&nbsp;&#xB7;
<a href="#ANY">ANY</a>&nbsp;&#xB7;
<a href="#CATEGORY">CATEGORY</a>&nbsp;&#xB7;
<a href="#EVERY">EVERY</a>&nbsp;&#xB7;
<a href="#SITE">SITE</a>&nbsp;&#xB7;
<a href="#URL">URL</a>
</div>
<div class="right_bar_title"><a href="#LOGIC_OPS"><? loc LOGIC_OPERATORS_HEADING ?></div>
<div class="right_bar_item">
<a href="#AND">AND</a>&nbsp;&#xB7;
<a href="#EXCEPT">EXCEPT</a>&nbsp;&#xB7;
<a href="#OR">OR</a>
</div>
<div class="right_bar_title"><a href="#RESTRICTING_OPS"><? loc RESTRICTING_OPERATORS_HEADING ?></div>
<div class="right_bar_item">
<a href="#CAPACITY">CAPACITY</a>&nbsp;&#xB7;
<a href="#COUNTRY">COUNTRY</a>&nbsp;&#xB7;
<a href="#DATE">DATE</a>&nbsp;&#xB7;
<a href="#DOMAIN">DOMAIN</a>&nbsp;&#xB7;
<a href="#FETCHED">FETCHED</a>&nbsp;&#xB7;
<a href="#LANGUAGE">LANGUAGE</a>&nbsp;&#xB7;
<a href="#VISITED">VISITED</a>&nbsp;&#xB7;
<a href="#WITH">WITH</a>
</div>
<div class="right_bar_title"><a href="#TIME"><? loc TIME_HEADING ?></div>
</td>
</tr>
</table>

<div id="copyright" valign="bottom"><? conf copyright_note ?> <? loc COPYRIGHT ?> <a href="/psp/<? lang ?>/contact"><? loc CONTACT ?></a></div>

</body>
</html>
