<??>xml version="1.0" encoding="UTF-8"?>
<items>
  <item type="id-pefix" value="&lt;table class='item_table'>&lt;tr>&lt;td class='item_id' valign='top'>"/>
  <item type="id-suffix" value="&lt;/td>&lt;td>"/>
  <item type="value-suffix" value="&lt;/td>&lt;/tr>&lt;/table>"/>

  <item type="output" value="&lt;table class='items_table'>&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="A - B - C &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="ABW" value="<? loc ABW ?>"/>
  <item id="AFG" value="<? loc AFG ?>"/>
  <item id="AGO" value="<? loc AGO ?>"/>
  <item id="AIA" value="<? loc AIA ?>"/>
  <item id="ALB" value="<? loc ALB ?>"/>
  <item id="ANT" value="<? loc ANT ?>"/>
  <item id="AND" value="<? loc AND ?>"/>
  <item id="ARG" value="<? loc ARG ?>"/>
  <item id="ARM" value="<? loc ARM ?>"/>
  <item id="ASM" value="<? loc ASM ?>"/>
  <item id="ATF" value="<? loc ATF ?>"/>
  <item id="ATG" value="<? loc ATG ?>"/>
  <item id="AUS" value="<? loc AUS ?>"/>
  <item id="AUT" value="<? loc AUT ?>"/>
  <item id="AZE" value="<? loc AZE ?>"/>
  <item id="ARE" value="<? loc ARE ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="BDI" value="<? loc BDI ?>"/>
  <item id="BEL" value="<? loc BEL ?>"/>
  <item id="BEN" value="<? loc BEN ?>"/>
  <item id="BGD" value="<? loc BGD ?>"/>
  <item id="BFA" value="<? loc BFA ?>"/>
  <item id="BGR" value="<? loc BGR ?>"/>
  <item id="BHS" value="<? loc BHS ?>"/>
  <item id="BHR" value="<? loc BHR ?>"/>
  <item id="BIH" value="<? loc BIH ?>"/>
  <item id="BLR" value="<? loc BLR ?>"/>
  <item id="BLZ" value="<? loc BLZ ?>"/>
  <item id="BMU" value="<? loc BMU ?>"/>
  <item id="BOL" value="<? loc BOL ?>"/>
  <item id="BRA" value="<? loc BRA ?>"/>
  <item id="BRB" value="<? loc BRB ?>"/>
  <item id="BRN" value="<? loc BRN ?>"/>
  <item id="BTN" value="<? loc BTN ?>"/>
  <item id="BVT" value="<? loc BVT ?>"/>
  <item id="BWA" value="<? loc BWA ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="CAF" value="<? loc CAF ?>"/>
  <item id="CAN" value="<? loc CAN ?>"/>
  <item id="CCK" value="<? loc CCK ?>"/>
  <item id="CHE" value="<? loc CHE ?>"/>
  <item id="CHL" value="<? loc CHL ?>"/>
  <item id="CHN" value="<? loc CHN ?>"/>
  <item id="CIV" value="<? loc CIV ?>"/>
  <item id="CMR" value="<? loc CMR ?>"/>
  <item id="COD" value="<? loc COD ?>"/>
  <item id="COG" value="<? loc COG ?>"/>
  <item id="COK" value="<? loc COK ?>"/>
  <item id="COL" value="<? loc COL ?>"/>
  <item id="COM" value="<? loc COM ?>"/>
  <item id="CPV" value="<? loc CPV ?>"/>
  <item id="CRI" value="<? loc CRI ?>"/>
  <item id="CUB" value="<? loc CUB ?>"/>
  <item id="CXR" value="<? loc CXR ?>"/>
  <item id="CYM" value="<? loc CYM ?>"/>
  <item id="CYP" value="<? loc CYP ?>"/>
  <item id="CZE" value="<? loc CZE ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="D - E - F &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="DEU" value="<? loc DEU ?>"/>
  <item id="DJI" value="<? loc DJI ?>"/>
  <item id="DNK" value="<? loc DNK ?>"/>
  <item id="DMA" value="<? loc DMA ?>"/>
  <item id="DOM" value="<? loc DOM ?>"/>
  <item id="DZA" value="<? loc DZA ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="ECU" value="<? loc ECU ?>"/>
  <item id="EGY" value="<? loc EGY ?>"/>
  <item id="ERI" value="<? loc ERI ?>"/>
  <item id="ESH" value="<? loc ESH ?>"/>
  <item id="ESP" value="<? loc ESP ?>"/>
  <item id="EST" value="<? loc EST ?>"/>
  <item id="ETH" value="<? loc ETH ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="FIN" value="<? loc FIN ?>"/>
  <item id="FJI" value="<? loc FJI ?>"/>
  <item id="FLK" value="<? loc FLK ?>"/>
  <item id="FRA" value="<? loc FRA ?>"/>
  <item id="FRO" value="<? loc FRO ?>"/>
  <item id="FSM" value="<? loc FSM ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="G - H - I &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="GAB" value="<? loc GAB ?>"/>
  <item id="GBR" value="<? loc GBR ?>"/>
  <item id="GEO" value="<? loc GEO ?>"/>
  <item id="GHA" value="<? loc GHA ?>"/>
  <item id="GIB" value="<? loc GIB ?>"/>
  <item id="GIN" value="<? loc GIN ?>"/>
  <item id="GLP" value="<? loc GLP ?>"/>
  <item id="GMB" value="<? loc GMB ?>"/>
  <item id="GNB" value="<? loc GNB ?>"/>
  <item id="GNQ" value="<? loc GNQ ?>"/>
  <item id="GRC" value="<? loc GRC ?>"/>
  <item id="GRD" value="<? loc GRD ?>"/>
  <item id="GRL" value="<? loc GRL ?>"/>
  <item id="GTM" value="<? loc GTM ?>"/>
  <item id="GUF" value="<? loc GUF ?>"/>
  <item id="GUM" value="<? loc GUM ?>"/>
  <item id="GUY" value="<? loc GUY ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="HKG" value="<? loc HKG ?>"/>
  <item id="HMD" value="<? loc HMD ?>"/>
  <item id="HND" value="<? loc HND ?>"/>
  <item id="HRV" value="<? loc HRV ?>"/>
  <item id="HTI" value="<? loc HTI ?>"/>
  <item id="HUN" value="<? loc HUN ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="IDN" value="<? loc IDN ?>"/>
  <item id="IND" value="<? loc IND ?>"/>
  <item id="IOT" value="<? loc IOT ?>"/>
  <item id="IRL" value="<? loc IRL ?>"/>
  <item id="IRN" value="<? loc IRN ?>"/>
  <item id="IRQ" value="<? loc IRQ ?>"/>
  <item id="ISL" value="<? loc ISL ?>"/>
  <item id="ISR" value="<? loc ISR ?>"/>
  <item id="ITA" value="<? loc ITA ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="J - K - L &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="JAM" value="<? loc JAM ?>"/>
  <item id="JOR" value="<? loc JOR ?>"/>
  <item id="JPN" value="<? loc JPN ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="KAZ" value="<? loc KAZ ?>"/>
  <item id="KEN" value="<? loc KEN ?>"/>
  <item id="KGZ" value="<? loc KGZ ?>"/>
  <item id="KHM" value="<? loc KHM ?>"/>
  <item id="KIR" value="<? loc KIR ?>"/>
  <item id="KNA" value="<? loc KNA ?>"/>
  <item id="KOR" value="<? loc KOR ?>"/>
  <item id="KWT" value="<? loc KWT ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="LAO" value="<? loc LAO ?>"/>
  <item id="LBN" value="<? loc LBN ?>"/>
  <item id="LBR" value="<? loc LBR ?>"/>
  <item id="LBY" value="<? loc LBY ?>"/>
  <item id="LCA" value="<? loc LCA ?>"/>
  <item id="LIE" value="<? loc LIE ?>"/>
  <item id="LKA" value="<? loc LKA ?>"/>
  <item id="LSO" value="<? loc LSO ?>"/>
  <item id="LTU" value="<? loc LTU ?>"/>
  <item id="LUX" value="<? loc LUX ?>"/>
  <item id="LVA" value="<? loc LVA ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="M - N - O &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="MAC" value="<? loc MAC ?>"/>
  <item id="MAR" value="<? loc MAR ?>"/>
  <item id="MCO" value="<? loc MCO ?>"/>
  <item id="MDA" value="<? loc MDA ?>"/>
  <item id="MDG" value="<? loc MDG ?>"/>
  <item id="MDV" value="<? loc MDV ?>"/>
  <item id="MEX" value="<? loc MEX ?>"/>
  <item id="MHL" value="<? loc MHL ?>"/>
  <item id="MKD" value="<? loc MKD ?>"/>
  <item id="MLI" value="<? loc MLI ?>"/>
  <item id="MLT" value="<? loc MLT ?>"/>
  <item id="MMR" value="<? loc MMR ?>"/>
  <item id="MNG" value="<? loc MNG ?>"/>
  <item id="MNP" value="<? loc MNP ?>"/>
  <item id="MOZ" value="<? loc MOZ ?>"/>
  <item id="MRT" value="<? loc MRT ?>"/>
  <item id="MSR" value="<? loc MSR ?>"/>
  <item id="MTQ" value="<? loc MTQ ?>"/>
  <item id="MUS" value="<? loc MUS ?>"/>
  <item id="MWI" value="<? loc MWI ?>"/>
  <item id="MYS" value="<? loc MYS ?>"/>
  <item id="MYT" value="<? loc MYT ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="NAM" value="<? loc NAM ?>"/>
  <item id="NER" value="<? loc NER ?>"/>
  <item id="NCL" value="<? loc NCL ?>"/>
  <item id="NFK" value="<? loc NFK ?>"/>
  <item id="NGA" value="<? loc NGA ?>"/>
  <item id="NIC" value="<? loc NIC ?>"/>
  <item id="NIU" value="<? loc NIU ?>"/>
  <item id="NLD" value="<? loc NLD ?>"/>
  <item id="NOR" value="<? loc NOR ?>"/>
  <item id="NPL" value="<? loc NPL ?>"/>
  <item id="NRU" value="<? loc NRU ?>"/>
  <item id="NZL" value="<? loc NZL ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="OMN" value="<? loc OMN ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="P - Q - R &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="PAK" value="<? loc PAK ?>"/>
  <item id="PAN" value="<? loc PAN ?>"/>
  <item id="PCN" value="<? loc PCN ?>"/>
  <item id="PER" value="<? loc PER ?>"/>
  <item id="PHL" value="<? loc PHL ?>"/>
  <item id="PLW" value="<? loc PLW ?>"/>
  <item id="PNG" value="<? loc PNG ?>"/>
  <item id="POL" value="<? loc POL ?>"/>
  <item id="PRI" value="<? loc PRI ?>"/>
  <item id="PRK" value="<? loc PRK ?>"/>
  <item id="PRT" value="<? loc PRT ?>"/>
  <item id="PRY" value="<? loc PRY ?>"/>
  <item id="PSE" value="<? loc PSE ?>"/>
  <item id="PYF" value="<? loc PYF ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="QAT" value="<? loc QAT ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="REU" value="<? loc REU ?>"/>
  <item id="ROU" value="<? loc ROU ?>"/>
  <item id="RUS" value="<? loc RUS ?>"/>
  <item id="RWA" value="<? loc RWA ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="S - T - U &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="SAU" value="<? loc SAU ?>"/>
  <item id="SCG" value="<? loc SCG ?>"/>
  <item id="SDN" value="<? loc SDN ?>"/>
  <item id="SEN" value="<? loc SEN ?>"/>
  <item id="SGP" value="<? loc SGP ?>"/>
  <item id="SGS" value="<? loc SGS ?>"/>
  <item id="SHN" value="<? loc SHN ?>"/>
  <item id="SJM" value="<? loc SJM ?>"/>
  <item id="SLB" value="<? loc SLB ?>"/>
  <item id="SLE" value="<? loc SLE ?>"/>
  <item id="SLV" value="<? loc SLV ?>"/>
  <item id="SMR" value="<? loc SMR ?>"/>
  <item id="SOM" value="<? loc SOM ?>"/>
  <item id="SPM" value="<? loc SPM ?>"/>
  <item id="STP" value="<? loc STP ?>"/>
  <item id="SUR" value="<? loc SUR ?>"/>
  <item id="SVK" value="<? loc SVK ?>"/>
  <item id="SVN" value="<? loc SVN ?>"/>
  <item id="SWE" value="<? loc SWE ?>"/>
  <item id="SWZ" value="<? loc SWZ ?>"/>
  <item id="SYC" value="<? loc SYC ?>"/>
  <item id="SYR" value="<? loc SYR ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="TCA" value="<? loc TCA ?>"/>
  <item id="TCD" value="<? loc TCD ?>"/>
  <item id="TGO" value="<? loc TGO ?>"/>
  <item id="THA" value="<? loc THA ?>"/>
  <item id="TJK" value="<? loc TJK ?>"/>
  <item id="TKL" value="<? loc TKL ?>"/>
  <item id="TKM" value="<? loc TKM ?>"/>
  <item id="TLS" value="<? loc TLS ?>"/>
  <item id="TON" value="<? loc TON ?>"/>
  <item id="TUR" value="<? loc TUR ?>"/>
  <item id="TTO" value="<? loc TTO ?>"/>
  <item id="TUN" value="<? loc TUN ?>"/>
  <item id="TUV" value="<? loc TUV ?>"/>
  <item id="TWN" value="<? loc TWN ?>"/>
  <item id="TZA" value="<? loc TZA ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="UGA" value="<? loc UGA ?>"/>
  <item id="UKR" value="<? loc UKR ?>"/>
  <item id="UMI" value="<? loc UMI ?>"/>
  <item id="URY" value="<? loc URY ?>"/>
  <item id="USA" value="<? loc USA ?>"/>
  <item id="UZB" value="<? loc UZB ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="V - W - X &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="VAT" value="<? loc VAT ?>"/>
  <item id="VCT" value="<? loc VCT ?>"/>
  <item id="VEN" value="<? loc VEN ?>"/>
  <item id="VGB" value="<? loc VGB ?>"/>
  <item id="VIR" value="<? loc VIR ?>"/>
  <item id="VNM" value="<? loc VNM ?>"/>
  <item id="VUT" value="<? loc VUT ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="WSM" value="<? loc WSM ?>"/>
  <item id="WLF" value="<? loc WLF ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="Y - Z &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="YEM" value="<? loc YEM ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="ZAF" value="<? loc ZAF ?>"/>
  <item id="ZMB" value="<? loc ZMB ?>"/>
  <item id="ZWE" value="<? loc ZWE ?>"/>

</items>
