<??>xml version="1.0" encoding="UTF-8"?>
<items>
  <item type="id-pefix" value="&lt;tr>&lt;td class='item_id'>"/>
  <item type="id-suffix" value="&lt;/td>&lt;td>"/>
  <item type="value-suffix" value="&lt;/td>&lt;/tr>"/>

  <item type="output" value="&lt;table class='items_table'>"/>
  <item id="atom" value="<? loc atom ?>"/>
  <item id="rdf" value="<? loc rdf ?>"/>
  <item id="rss" value="<? loc rss ?>"/>
  <item type="output" value="&lt;/table>"/>
</items>
