<??>xml version="1.0" encoding="UTF-8"?>
<items>
  <item type="id-pefix" value="&lt;table class='item_table'>&lt;tr>&lt;td class='item_id' valign='top'>"/>
  <item type="id-suffix" value="&lt;/td>&lt;td>"/>
  <item type="value-suffix" value="&lt;/td>&lt;/tr>&lt;/table>"/>

  <item type="output" value="&lt;table class='items_table'>&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="A - B - C &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="aar" value="<? loc aar ?>"/>
  <item id="abk" value="<? loc abk ?>"/>
  <item id="ace" value="<? loc ace ?>"/>
  <item id="ach" value="<? loc ach ?>"/>
  <item id="ada" value="<? loc ada ?>"/>
  <item id="ady" value="<? loc ady ?>"/>
  <item id="afa" value="<? loc afa ?>"/>
  <item id="afh" value="<? loc afh ?>"/>
  <item id="afr" value="<? loc afr ?>"/>
  <item id="ain" value="<? loc ain ?>"/>
  <item id="aka" value="<? loc aka ?>"/>
  <item id="akk" value="<? loc akk ?>"/>
  <item id="alb" value="<? loc alb ?>"/>
  <item id="ale" value="<? loc ale ?>"/>
  <item id="alg" value="<? loc alg ?>"/>
  <item id="alt" value="<? loc alt ?>"/>
  <item id="amh" value="<? loc amh ?>"/>
  <item id="ang" value="<? loc ang ?>"/>
  <item id="anp" value="<? loc anp ?>"/>
  <item id="apa" value="<? loc apa ?>"/>
  <item id="ara" value="<? loc ara ?>"/>
  <item id="arc" value="<? loc arc ?>"/>
  <item id="arg" value="<? loc arg ?>"/>
  <item id="arm" value="<? loc arm ?>"/>
  <item id="arn" value="<? loc arn ?>"/>
  <item id="arp" value="<? loc arp ?>"/>
  <item id="arw" value="<? loc arw ?>"/>
  <item id="asm" value="<? loc asm ?>"/>
  <item id="ast" value="<? loc ast ?>"/>
  <item id="ath" value="<? loc ath ?>"/>
  <item id="aus" value="<? loc aus ?>"/>
  <item id="ava" value="<? loc ava ?>"/>
  <item id="ave" value="<? loc ave ?>"/>
  <item id="awa" value="<? loc awa ?>"/>
  <item id="aym" value="<? loc aym ?>"/>
  <item id="aze" value="<? loc aze ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="bad" value="<? loc bad ?>"/>
  <item id="bai" value="<? loc bai ?>"/>
  <item id="bak" value="<? loc bak ?>"/>
  <item id="bal" value="<? loc bal ?>"/>
  <item id="bam" value="<? loc bam ?>"/>
  <item id="ban" value="<? loc ban ?>"/>
  <item id="baq" value="<? loc baq ?>"/>
  <item id="bas" value="<? loc bas ?>"/>
  <item id="bat" value="<? loc bat ?>"/>
  <item id="bej" value="<? loc bej ?>"/>
  <item id="bel" value="<? loc bel ?>"/>
  <item id="bem" value="<? loc bem ?>"/>
  <item id="ben" value="<? loc ben ?>"/>
  <item id="ber" value="<? loc ber ?>"/>
  <item id="bho" value="<? loc bho ?>"/>
  <item id="bih" value="<? loc bih ?>"/>
  <item id="bik" value="<? loc bik ?>"/>
  <item id="bin" value="<? loc bin ?>"/>
  <item id="bis" value="<? loc bis ?>"/>
  <item id="bla" value="<? loc bla ?>"/>
  <item id="bnt" value="<? loc bnt ?>"/>
  <item id="bos" value="<? loc bos ?>"/>
  <item id="bra" value="<? loc bra ?>"/>
  <item id="bre" value="<? loc bre ?>"/>
  <item id="btk" value="<? loc btk ?>"/>
  <item id="bua" value="<? loc bua ?>"/>
  <item id="bug" value="<? loc bug ?>"/>
  <item id="bul" value="<? loc bul ?>"/>
  <item id="bur" value="<? loc bur ?>"/>
  <item id="byn" value="<? loc byn ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="cad" value="<? loc cad ?>"/>
  <item id="cai" value="<? loc cai ?>"/>
  <item id="car" value="<? loc car ?>"/>
  <item id="cat" value="<? loc cat ?>"/>
  <item id="cau" value="<? loc cau ?>"/>
  <item id="ceb" value="<? loc ceb ?>"/>
  <item id="cel" value="<? loc cel ?>"/>
  <item id="cha" value="<? loc cha ?>"/>
  <item id="chb" value="<? loc chb ?>"/>
  <item id="che" value="<? loc che ?>"/>
  <item id="chg" value="<? loc chg ?>"/>
  <item id="chi" value="<? loc chi ?>"/>
  <item id="chk" value="<? loc chk ?>"/>
  <item id="chm" value="<? loc chm ?>"/>
  <item id="chn" value="<? loc chn ?>"/>
  <item id="cho" value="<? loc cho ?>"/>
  <item id="chp" value="<? loc chp ?>"/>
  <item id="chr" value="<? loc chr ?>"/>
  <item id="chu" value="<? loc chu ?>"/>
  <item id="chv" value="<? loc chv ?>"/>
  <item id="chy" value="<? loc chy ?>"/>
  <item id="cmc" value="<? loc cmc ?>"/>
  <item id="cop" value="<? loc cop ?>"/>
  <item id="cor" value="<? loc cor ?>"/>
  <item id="cos" value="<? loc cos ?>"/>
  <item id="cpe" value="<? loc cpe ?>"/>
  <item id="cpf" value="<? loc cpf ?>"/>
  <item id="cpp" value="<? loc cpp ?>"/>
  <item id="cre" value="<? loc cre ?>"/>
  <item id="crh" value="<? loc crh ?>"/>
  <item id="crp" value="<? loc crp ?>"/>
  <item id="csb" value="<? loc csb ?>"/>
  <item id="cus" value="<? loc cus ?>"/>
  <item id="cze" value="<? loc cze ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="D - E - F &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="dak" value="<? loc dak ?>"/>
  <item id="dan" value="<? loc dan ?>"/>
  <item id="dar" value="<? loc dar ?>"/>
  <item id="day" value="<? loc day ?>"/>
  <item id="del" value="<? loc del ?>"/>
  <item id="den" value="<? loc den ?>"/>
  <item id="dgr" value="<? loc dgr ?>"/>
  <item id="din" value="<? loc din ?>"/>
  <item id="div" value="<? loc div ?>"/>
  <item id="doi" value="<? loc doi ?>"/>
  <item id="dra" value="<? loc dra ?>"/>
  <item id="dsb" value="<? loc dsb ?>"/>
  <item id="dua" value="<? loc dua ?>"/>
  <item id="dum" value="<? loc dum ?>"/>
  <item id="dut" value="<? loc dut ?>"/>
  <item id="dyu" value="<? loc dyu ?>"/>
  <item id="dzo" value="<? loc dzo ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="efi" value="<? loc efi ?>"/>
  <item id="egy" value="<? loc egy ?>"/>
  <item id="eka" value="<? loc eka ?>"/>
  <item id="elx" value="<? loc elx ?>"/>
  <item id="eng" value="<? loc eng ?>"/>
  <item id="enm" value="<? loc enm ?>"/>
  <item id="epo" value="<? loc epo ?>"/>
  <item id="est" value="<? loc est ?>"/>
  <item id="ewe" value="<? loc ewe ?>"/>
  <item id="ewo" value="<? loc ewo ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="fan" value="<? loc fan ?>"/>
  <item id="fao" value="<? loc fao ?>"/>
  <item id="fat" value="<? loc fat ?>"/>
  <item id="fij" value="<? loc fij ?>"/>
  <item id="fil" value="<? loc fil ?>"/>
  <item id="fin" value="<? loc fin ?>"/>
  <item id="fiu" value="<? loc fiu ?>"/>
  <item id="fon" value="<? loc fon ?>"/>
  <item id="fre" value="<? loc fre ?>"/>
  <item id="frm" value="<? loc frm ?>"/>
  <item id="fro" value="<? loc fro ?>"/>
  <item id="frr" value="<? loc frr ?>"/>
  <item id="frs" value="<? loc frs ?>"/>
  <item id="fry" value="<? loc fry ?>"/>
  <item id="ful" value="<? loc ful ?>"/>
  <item id="fur" value="<? loc fur ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="G - H - I &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="gaa" value="<? loc gaa ?>"/>
  <item id="gay" value="<? loc gay ?>"/>
  <item id="gba" value="<? loc gba ?>"/>
  <item id="gem" value="<? loc gem ?>"/>
  <item id="geo" value="<? loc geo ?>"/>
  <item id="ger" value="<? loc ger ?>"/>
  <item id="gez" value="<? loc gez ?>"/>
  <item id="gil" value="<? loc gil ?>"/>
  <item id="gla" value="<? loc gla ?>"/>
  <item id="gle" value="<? loc gle ?>"/>
  <item id="glg" value="<? loc glg ?>"/>
  <item id="glv" value="<? loc glv ?>"/>
  <item id="gmh" value="<? loc gmh ?>"/>
  <item id="goh" value="<? loc goh ?>"/>
  <item id="gon" value="<? loc gon ?>"/>
  <item id="gor" value="<? loc gor ?>"/>
  <item id="got" value="<? loc got ?>"/>
  <item id="grb" value="<? loc grb ?>"/>
  <item id="grc" value="<? loc grc ?>"/>
  <item id="gre" value="<? loc gre ?>"/>
  <item id="grn" value="<? loc grn ?>"/>
  <item id="gsw" value="<? loc gsw ?>"/>
  <item id="guj" value="<? loc guj ?>"/>
  <item id="gwi" value="<? loc gwi ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="hai" value="<? loc hai ?>"/>
  <item id="hat" value="<? loc hat ?>"/>
  <item id="hau" value="<? loc hau ?>"/>
  <item id="haw" value="<? loc haw ?>"/>
  <item id="heb" value="<? loc heb ?>"/>
  <item id="her" value="<? loc her ?>"/>
  <item id="hil" value="<? loc hil ?>"/>
  <item id="him" value="<? loc him ?>"/>
  <item id="hin" value="<? loc hin ?>"/>
  <item id="hit" value="<? loc hit ?>"/>
  <item id="hmn" value="<? loc hmn ?>"/>
  <item id="hmo" value="<? loc hmo ?>"/>
  <item id="hsb" value="<? loc hsb ?>"/>
  <item id="hun" value="<? loc hun ?>"/>
  <item id="hup" value="<? loc hup ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="iba" value="<? loc iba ?>"/>
  <item id="ibo" value="<? loc ibo ?>"/>
  <item id="ice" value="<? loc ice ?>"/>
  <item id="ido" value="<? loc ido ?>"/>
  <item id="iii" value="<? loc iii ?>"/>
  <item id="ijo" value="<? loc ijo ?>"/>
  <item id="iku" value="<? loc iku ?>"/>
  <item id="ile" value="<? loc ile ?>"/>
  <item id="ilo" value="<? loc ilo ?>"/>
  <item id="ina" value="<? loc ina ?>"/>
  <item id="inc" value="<? loc inc ?>"/>
  <item id="ind" value="<? loc ind ?>"/>
  <item id="ine" value="<? loc ine ?>"/>
  <item id="inh" value="<? loc inh ?>"/>
  <item id="ipk" value="<? loc ipk ?>"/>
  <item id="ira" value="<? loc ira ?>"/>
  <item id="iro" value="<? loc iro ?>"/>
  <item id="ita" value="<? loc ita ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="J - K - L &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="jav" value="<? loc jav ?>"/>
  <item id="jbo" value="<? loc jbo ?>"/>
  <item id="jpn" value="<? loc jpn ?>"/>
  <item id="jpr" value="<? loc jpr ?>"/>
  <item id="jrb" value="<? loc jrb ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="kaa" value="<? loc kaa ?>"/>
  <item id="kab" value="<? loc kab ?>"/>
  <item id="kac" value="<? loc kac ?>"/>
  <item id="kal" value="<? loc kal ?>"/>
  <item id="kam" value="<? loc kam ?>"/>
  <item id="kan" value="<? loc kan ?>"/>
  <item id="kar" value="<? loc kar ?>"/>
  <item id="kas" value="<? loc kas ?>"/>
  <item id="kau" value="<? loc kau ?>"/>
  <item id="kaw" value="<? loc kaw ?>"/>
  <item id="kaz" value="<? loc kaz ?>"/>
  <item id="kbd" value="<? loc kbd ?>"/>
  <item id="kha" value="<? loc kha ?>"/>
  <item id="khi" value="<? loc khi ?>"/>
  <item id="khm" value="<? loc khm ?>"/>
  <item id="kho" value="<? loc kho ?>"/>
  <item id="kik" value="<? loc kik ?>"/>
  <item id="kin" value="<? loc kin ?>"/>
  <item id="kir" value="<? loc kir ?>"/>
  <item id="kmb" value="<? loc kmb ?>"/>
  <item id="kok" value="<? loc kok ?>"/>
  <item id="kom" value="<? loc kom ?>"/>
  <item id="kon" value="<? loc kon ?>"/>
  <item id="kor" value="<? loc kor ?>"/>
  <item id="kos" value="<? loc kos ?>"/>
  <item id="kpe" value="<? loc kpe ?>"/>
  <item id="krc" value="<? loc krc ?>"/>
  <item id="krl" value="<? loc krl ?>"/>
  <item id="kro" value="<? loc kro ?>"/>
  <item id="kru" value="<? loc kru ?>"/>
  <item id="kua" value="<? loc kua ?>"/>
  <item id="kum" value="<? loc kum ?>"/>
  <item id="kur" value="<? loc kur ?>"/>
  <item id="kut" value="<? loc kut ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="lad" value="<? loc lad ?>"/>
  <item id="lah" value="<? loc lah ?>"/>
  <item id="lam" value="<? loc lam ?>"/>
  <item id="lao" value="<? loc lao ?>"/>
  <item id="lat" value="<? loc lat ?>"/>
  <item id="lav" value="<? loc lav ?>"/>
  <item id="lez" value="<? loc lez ?>"/>
  <item id="lim" value="<? loc lim ?>"/>
  <item id="lin" value="<? loc lin ?>"/>
  <item id="lit" value="<? loc lit ?>"/>
  <item id="lol" value="<? loc lol ?>"/>
  <item id="loz" value="<? loc loz ?>"/>
  <item id="ltz" value="<? loc ltz ?>"/>
  <item id="lua" value="<? loc lua ?>"/>
  <item id="lub" value="<? loc lub ?>"/>
  <item id="lug" value="<? loc lug ?>"/>
  <item id="lui" value="<? loc lui ?>"/>
  <item id="lun" value="<? loc lun ?>"/>
  <item id="luo" value="<? loc luo ?>"/>
  <item id="lus" value="<? loc lus ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="M - N - O &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="mac" value="<? loc mac ?>"/>
  <item id="mad" value="<? loc mad ?>"/>
  <item id="mag" value="<? loc mag ?>"/>
  <item id="mah" value="<? loc mah ?>"/>
  <item id="mai" value="<? loc mai ?>"/>
  <item id="mak" value="<? loc mak ?>"/>
  <item id="mal" value="<? loc mal ?>"/>
  <item id="man" value="<? loc man ?>"/>
  <item id="mao" value="<? loc mao ?>"/>
  <item id="map" value="<? loc map ?>"/>
  <item id="mar" value="<? loc mar ?>"/>
  <item id="mas" value="<? loc mas ?>"/>
  <item id="may" value="<? loc may ?>"/>
  <item id="mdf" value="<? loc mdf ?>"/>
  <item id="mdr" value="<? loc mdr ?>"/>
  <item id="men" value="<? loc men ?>"/>
  <item id="mga" value="<? loc mga ?>"/>
  <item id="mic" value="<? loc mic ?>"/>
  <item id="min" value="<? loc min ?>"/>
  <item id="mkh" value="<? loc mkh ?>"/>
  <item id="mlg" value="<? loc mlg ?>"/>
  <item id="mlt" value="<? loc mlt ?>"/>
  <item id="mnc" value="<? loc mnc ?>"/>
  <item id="mni" value="<? loc mni ?>"/>
  <item id="mno" value="<? loc mno ?>"/>
  <item id="moh" value="<? loc moh ?>"/>
  <item id="mol" value="<? loc mol ?>"/>
  <item id="mon" value="<? loc mon ?>"/>
  <item id="mos" value="<? loc mos ?>"/>
  <item id="mun" value="<? loc mun ?>"/>
  <item id="mus" value="<? loc mus ?>"/>
  <item id="mwl" value="<? loc mwl ?>"/>
  <item id="mwr" value="<? loc mwr ?>"/>
  <item id="myn" value="<? loc myn ?>"/>
  <item id="myv" value="<? loc myv ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="nah" value="<? loc nah ?>"/>
  <item id="nai" value="<? loc nai ?>"/>
  <item id="nap" value="<? loc nap ?>"/>
  <item id="nau" value="<? loc nau ?>"/>
  <item id="nav" value="<? loc nav ?>"/>
  <item id="nbl" value="<? loc nbl ?>"/>
  <item id="nde" value="<? loc nde ?>"/>
  <item id="ndo" value="<? loc ndo ?>"/>
  <item id="nds" value="<? loc nds ?>"/>
  <item id="nep" value="<? loc nep ?>"/>
  <item id="new" value="<? loc new ?>"/>
  <item id="nia" value="<? loc nia ?>"/>
  <item id="nic" value="<? loc nic ?>"/>
  <item id="niu" value="<? loc niu ?>"/>
  <item id="nno" value="<? loc nno ?>"/>
  <item id="nob" value="<? loc nob ?>"/>
  <item id="nog" value="<? loc nog ?>"/>
  <item id="non" value="<? loc non ?>"/>
  <item id="nor" value="<? loc nor ?>"/>
  <item id="nso" value="<? loc nso ?>"/>
  <item id="nub" value="<? loc nub ?>"/>
  <item id="nwc" value="<? loc nwc ?>"/>
  <item id="nya" value="<? loc nya ?>"/>
  <item id="nym" value="<? loc nym ?>"/>
  <item id="nyn" value="<? loc nyn ?>"/>
  <item id="nyo" value="<? loc nyo ?>"/>
  <item id="nzi" value="<? loc nzi ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="oci" value="<? loc oci ?>"/>
  <item id="oji" value="<? loc oji ?>"/>
  <item id="ori" value="<? loc ori ?>"/>
  <item id="orm" value="<? loc orm ?>"/>
  <item id="osa" value="<? loc osa ?>"/>
  <item id="oss" value="<? loc oss ?>"/>
  <item id="ota" value="<? loc ota ?>"/>
  <item id="oto" value="<? loc oto ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="P - Q - R &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="paa" value="<? loc paa ?>"/>
  <item id="pag" value="<? loc pag ?>"/>
  <item id="pal" value="<? loc pal ?>"/>
  <item id="pam" value="<? loc pam ?>"/>
  <item id="pan" value="<? loc pan ?>"/>
  <item id="pap" value="<? loc pap ?>"/>
  <item id="pau" value="<? loc pau ?>"/>
  <item id="peo" value="<? loc peo ?>"/>
  <item id="per" value="<? loc per ?>"/>
  <item id="phi" value="<? loc phi ?>"/>
  <item id="phn" value="<? loc phn ?>"/>
  <item id="pli" value="<? loc pli ?>"/>
  <item id="pol" value="<? loc pol ?>"/>
  <item id="pon" value="<? loc pon ?>"/>
  <item id="por" value="<? loc por ?>"/>
  <item id="pra" value="<? loc pra ?>"/>
  <item id="pro" value="<? loc pro ?>"/>
  <item id="pus" value="<? loc pus ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="que" value="<? loc que ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="raj" value="<? loc raj ?>"/>
  <item id="rap" value="<? loc rap ?>"/>
  <item id="rar" value="<? loc rar ?>"/>
  <item id="roa" value="<? loc roa ?>"/>
  <item id="roh" value="<? loc roh ?>"/>
  <item id="rom" value="<? loc rom ?>"/>
  <item id="rum" value="<? loc rum ?>"/>
  <item id="run" value="<? loc run ?>"/>
  <item id="rup" value="<? loc rup ?>"/>
  <item id="rus" value="<? loc rus ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="S - T - U &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="sad" value="<? loc sad ?>"/>
  <item id="sag" value="<? loc sag ?>"/>
  <item id="sah" value="<? loc sah ?>"/>
  <item id="sai" value="<? loc sai ?>"/>
  <item id="sal" value="<? loc sal ?>"/>
  <item id="sam" value="<? loc sam ?>"/>
  <item id="san" value="<? loc san ?>"/>
  <item id="sas" value="<? loc sas ?>"/>
  <item id="sat" value="<? loc sat ?>"/>
  <item id="scc" value="<? loc scc ?>"/>
  <item id="scn" value="<? loc scn ?>"/>
  <item id="sco" value="<? loc sco ?>"/>
  <item id="scr" value="<? loc scr ?>"/>
  <item id="sel" value="<? loc sel ?>"/>
  <item id="sem" value="<? loc sem ?>"/>
  <item id="sga" value="<? loc sga ?>"/>
  <item id="shn" value="<? loc shn ?>"/>
  <item id="sid" value="<? loc sid ?>"/>
  <item id="sin" value="<? loc sin ?>"/>
  <item id="sio" value="<? loc sio ?>"/>
  <item id="sit" value="<? loc sit ?>"/>
  <item id="sla" value="<? loc sla ?>"/>
  <item id="slo" value="<? loc slo ?>"/>
  <item id="slv" value="<? loc slv ?>"/>
  <item id="sma" value="<? loc sma ?>"/>
  <item id="sme" value="<? loc sme ?>"/>
  <item id="smi" value="<? loc smi ?>"/>
  <item id="smj" value="<? loc smj ?>"/>
  <item id="smn" value="<? loc smn ?>"/>
  <item id="smo" value="<? loc smo ?>"/>
  <item id="sms" value="<? loc sms ?>"/>
  <item id="sna" value="<? loc sna ?>"/>
  <item id="snd" value="<? loc snd ?>"/>
  <item id="snk" value="<? loc snk ?>"/>
  <item id="sog" value="<? loc sog ?>"/>
  <item id="som" value="<? loc som ?>"/>
  <item id="son" value="<? loc son ?>"/>
  <item id="sot" value="<? loc sot ?>"/>
  <item id="spa" value="<? loc spa ?>"/>
  <item id="srd" value="<? loc srd ?>"/>
  <item id="srn" value="<? loc srn ?>"/>
  <item id="srr" value="<? loc srr ?>"/>
  <item id="ssa" value="<? loc ssa ?>"/>
  <item id="ssw" value="<? loc ssw ?>"/>
  <item id="suk" value="<? loc suk ?>"/>
  <item id="sun" value="<? loc sun ?>"/>
  <item id="sus" value="<? loc sus ?>"/>
  <item id="sux" value="<? loc sux ?>"/>
  <item id="swa" value="<? loc swa ?>"/>
  <item id="swe" value="<? loc swe ?>"/>
  <item id="syr" value="<? loc syr ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="tah" value="<? loc tah ?>"/>
  <item id="tai" value="<? loc tai ?>"/>
  <item id="tam" value="<? loc tam ?>"/>
  <item id="tat" value="<? loc tat ?>"/>
  <item id="tel" value="<? loc tel ?>"/>
  <item id="tem" value="<? loc tem ?>"/>
  <item id="ter" value="<? loc ter ?>"/>
  <item id="tet" value="<? loc tet ?>"/>
  <item id="tgk" value="<? loc tgk ?>"/>
  <item id="tgl" value="<? loc tgl ?>"/>
  <item id="tha" value="<? loc tha ?>"/>
  <item id="tib" value="<? loc tib ?>"/>
  <item id="tig" value="<? loc tig ?>"/>
  <item id="tir" value="<? loc tir ?>"/>
  <item id="tiv" value="<? loc tiv ?>"/>
  <item id="tkl" value="<? loc tkl ?>"/>
  <item id="tlh" value="<? loc tlh ?>"/>
  <item id="tli" value="<? loc tli ?>"/>
  <item id="tmh" value="<? loc tmh ?>"/>
  <item id="tog" value="<? loc tog ?>"/>
  <item id="ton" value="<? loc ton ?>"/>
  <item id="tpi" value="<? loc tpi ?>"/>
  <item id="tsi" value="<? loc tsi ?>"/>
  <item id="tsn" value="<? loc tsn ?>"/>
  <item id="tso" value="<? loc tso ?>"/>
  <item id="tuk" value="<? loc tuk ?>"/>
  <item id="tum" value="<? loc tum ?>"/>
  <item id="tup" value="<? loc tup ?>"/>
  <item id="tur" value="<? loc tur ?>"/>
  <item id="tut" value="<? loc tut ?>"/>
  <item id="tvl" value="<? loc tvl ?>"/>
  <item id="twi" value="<? loc twi ?>"/>
  <item id="tyv" value="<? loc tyv ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="udm" value="<? loc udm ?>"/>
  <item id="uga" value="<? loc uga ?>"/>
  <item id="uig" value="<? loc uig ?>"/>
  <item id="ukr" value="<? loc ukr ?>"/>
  <item id="umb" value="<? loc umb ?>"/>
  <item id="urd" value="<? loc urd ?>"/>
  <item id="uzb" value="<? loc uzb ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="V - W - X &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="vai" value="<? loc vai ?>"/>
  <item id="ven" value="<? loc ven ?>"/>
  <item id="vie" value="<? loc vie ?>"/>
  <item id="vol" value="<? loc vol ?>"/>
  <item id="vot" value="<? loc vot ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="wak" value="<? loc wak ?>"/>
  <item id="wal" value="<? loc wal ?>"/>
  <item id="war" value="<? loc war ?>"/>
  <item id="was" value="<? loc was ?>"/>
  <item id="wel" value="<? loc wel ?>"/>
  <item id="wen" value="<? loc wen ?>"/>
  <item id="wln" value="<? loc wln ?>"/>
  <item id="wol" value="<? loc wol ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="xal" value="<? loc xal ?>"/>
  <item id="xho" value="<? loc xho ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td colspan='3' class='items_header'>"/>
  <item type="output" value="Y - Z &lt;/td>&lt;/tr>"/>
  <item type="output" value="&lt;tr>&lt;td valign='top' class='item_col'>"/>
  <item id="yao" value="<? loc yao ?>"/>
  <item id="yap" value="<? loc yap ?>"/>
  <item id="yid" value="<? loc yid ?>"/>
  <item id="yor" value="<? loc yor ?>"/>
  <item id="ypk" value="<? loc ypk ?>"/>
  <item type="output" value="&lt;/td>"/>
  <item type="output" value="&lt;td valign='top' class='item_col'>"/>
  <item id="zap" value="<? loc zap ?>"/>
  <item id="zen" value="<? loc zen ?>"/>
  <item id="zha" value="<? loc zha ?>"/>
  <item id="znd" value="<? loc znd ?>"/>
  <item id="zul" value="<? loc zul ?>"/>
  <item id="zun" value="<? loc zun ?>"/>
  <item type="output" value="&lt;/td>&lt;/tr>&lt;/table>"/>
</items>
