#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

source "$1/lib.sh"

echo_date "Adding 'O' value to 'protocol' column of StatSearchRequest table ..."

echo "alter table StatSearchRequest change column protocol protocol ENUM ('R', 'X', 'H', 'J', 'O') NOT NULL;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo_date "Adding 'O' value to 'protocol' column of StatPageImpression table ..."

echo "alter table StatPageImpression change column protocol protocol ENUM ('R', 'X', 'H', 'J', 'O') NOT NULL;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo_date "Adding 'O' value to 'protocol' column of StatPageImpressionBuff table ..."

echo "alter table StatPageImpressionBuff change column protocol protocol ENUM ('R', 'X', 'H', 'J', 'O') NOT NULL;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
