#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Creating StatMessageImpression table ..."

echo "create table StatMessageImpression ( \
      request_id CHAR(32) character set ascii NOT NULL \
        REFERENCES StatSearchRequest ( id ), \
      message_id BIGINT UNSIGNED NOT NULL, \
      time DATETIME NOT NULL, \
      time_usec MEDIUMINT UNSIGNED NOT NULL, \
      PRIMARY KEY (request_id, message_id) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo "Creating StatMessageClick table ..."

echo "create table StatMessageClick ( \
      request_id CHAR(32) character set ascii NOT NULL \
        REFERENCES StatSearchRequest ( id ), \
      message_id BIGINT UNSIGNED NOT NULL, \
      time DATETIME NOT NULL, \
      time_usec MEDIUMINT UNSIGNED NOT NULL, \
      PRIMARY KEY (request_id, message_id) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
