#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Adding optimized_query column to StatSearchRequest table ..."

echo "alter table StatSearchRequest add column optimized_query VARBINARY(1024) NOT NULL DEFAULT '' after response_suppressed_messages;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
