#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

source "$1/lib.sh"

echo_date "Cleaning EventBank service cache ..."

rm $3/Event/*.chn 2>/dev/null

echo "Done"

echo_date "Adding device_type to StatSearchRequest table ..."

echo "alter table StatSearchRequest \
add column device_type ENUM ('C', 'T', 'P', 'U') NOT NULL \
after client_os;" | ng-mysql --user root NewsGate

# No check as column can exist
#if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo_date "Adding device to StatSearchRequest table ..."

echo "alter table StatSearchRequest \
add column device VARCHAR(20) character set ascii NOT NULL \
after device_type;" | ng-mysql --user root NewsGate

# No check as column can exist
#if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

# Resets possibly non-zero $?
echo "" > /dev/null
