#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Cleaning MessageBank service cache ..."

rm $3/Message/* 2>/dev/null

# Resets possibly non-zero $?
echo "" > /dev/null

