#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

source "$1/lib.sh"

echo_date "Adding print_left_bar, add message_view to StatSearchRequest table ..."

echo "alter table StatSearchRequest \
add print_left_bar TINYINT NOT NULL DEFAULT 0 after translate_lang, \
add message_view ENUM ('P', 'L') NOT NULL DEFAULT 'P' after translate_lang;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
