#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Adding fetched column to Message table ..."

echo "alter table Message add column fetched INTEGER UNSIGNED NOT NULL DEFAULT 0 after updated;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then
  echo "Done"
else
  echo "Failed"
  exit 1
fi
