#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

source "$1/lib.sh"

echo_date "Cleaning MessageBank service cache ..."
rm $3/Message/Bank/* 2>/dev/null

echo_date "Cleaning RSSFeed services cache ..."
rm $3/RSSFeed/* 2>/dev/null

# Resets possibly non-zero $?
echo "" > /dev/null

echo_date "Adding keywords column to Feed table ..."

echo "alter table Feed add keywords TEXT after status;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo_date "Adding keywords_ column to FeedUpdateBuff table ..."

echo "alter table FeedUpdateBuff add keywords_ TEXT after status_;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
