#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

source "$1/lib.sh"

echo_date "Adding adjustment_script column to Feed table ..."

echo "alter table Feed add adjustment_script MEDIUMTEXT after keywords;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo_date "Adding adjustment_script_ column to FeedUpdateBuff table ..."

echo "alter table FeedUpdateBuff add adjustment_script_ MEDIUMTEXT after keywords_;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
