#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Altering Feed table ..."

echo "Adding lang column ..."

echo "alter table Feed add lang SMALLINT UNSIGNED NOT NULL DEFAULT 0xFFFF after space;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo "Adding country column ..."

echo "alter table Feed add country SMALLINT UNSIGNED NOT NULL DEFAULT 0xFFFF after lang;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo "Altering FeedUpdateBuff table ..."

echo "Adding lang_ column ..."

echo "alter table FeedUpdateBuff add lang_ SMALLINT UNSIGNED NOT NULL DEFAULT 0xFFFF after space_;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo "Adding country_ column ..."

echo "alter table FeedUpdateBuff add country_ SMALLINT UNSIGNED NOT NULL DEFAULT 0xFFFF after lang_;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
