#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

source "$1/lib.sh"

echo_date "Adding show_deleted to Moderator table ..."

echo "alter table Moderator \
add show_deleted ENUM ('Y', 'N') NOT NULL DEFAULT 'N' after status;" | \
ng-mysql --user root NewsGateModeration

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Inserting privileges ..."

echo "insert ignore into ModeratorPrivileges \
(moderator, privilege, granted_by) values (1, 9, 0), (1, 10, 0);" | \
ng-mysql --user root NewsGateModeration

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Filling Customer ..."

echo "insert ignore into Customer (id, status) values (1, 'E');" \
| ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table Advertiser ..."
echo "create table if not exists Advertiser ( \
      id BIGINT UNSIGNED NOT NULL PRIMARY KEY REFERENCES Customer ( id ), \
      name CHAR(128) NOT NULL UNIQUE KEY, \
      status ENUM ('E', 'D') NOT NULL, \
      max_ads_per_page INTEGER UNSIGNED NOT NULL DEFAULT 5 \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Filling Advertiser ..."

echo "insert ignore into Advertiser (id, status) values (1, 'E');" \
| ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdPage ..."
echo "create table if not exists AdPage ( \
      id INTEGER UNSIGNED NOT NULL PRIMARY KEY, \
      name CHAR(128) character set ascii NOT NULL UNIQUE KEY, \
      status ENUM ('E', 'D') NOT NULL, \
      max_ad_num INTEGER UNSIGNED NOT NULL \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Filling AdPage ..."

echo "insert ignore into AdPage \
(id, name, status, max_ad_num) values \
(1, 'Desktop Search, 2 Column Paper View', 'E', 8), \
(2, 'Desktop Search, Newsline View', 'E', 5), \
(3, 'Desktop Search, 1 Column Paper View', 'E', 7), \
(4, 'Tab Search, 2 Column Paper View', 'E', 8), \
(5, 'Tab Search, Newsline View', 'E', 5), \
(6, 'Tab Search, 1 Column Paper View', 'E', 7), \
(7, 'Mobile Search, Newsline View', 'E', 3), \
(8, 'Mobile Search, 1 Column Paper View', 'E', 5), \
(9, 'Desktop Message', 'E', 6), \
(10, 'Tab Message', 'E', 6), \
(11, 'Mobile Message', 'E', 4) \
;" \
| ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdSlot ..."
echo "create table if not exists AdSlot ( \
      id INTEGER UNSIGNED NOT NULL PRIMARY KEY, \
      page INTEGER UNSIGNED NOT NULL REFERENCES AdPage ( id ), \
      name CHAR(128) character set ascii NOT NULL UNIQUE KEY, \
      status ENUM ('E', 'D') NOT NULL, \
      min_width INTEGER UNSIGNED NOT NULL, \
      max_width INTEGER UNSIGNED NOT NULL, \
      min_height INTEGER UNSIGNED NOT NULL, \
      max_height INTEGER UNSIGNED NOT NULL \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Filling AdSlot ..."

echo "insert ignore into AdSlot \
(id, page, name, status, min_width, max_width, min_height, max_height) values \
(1, 1, 'Message 1 of Desktop Search, 2 Column Paper View', 'E', 30, 750, 10, 300), \
(2, 1, 'Message 2 of Desktop Search, 2 Column Paper View', 'E', 30, 750, 10, 300), \
(3, 1, 'Message Area 1 of Desktop Search, 2 Column Paper View', 'E', 30, 750, 10, 600), \
(4, 1, 'Message Area 2 of Desktop Search, 2 Column Paper View', 'E', 30, 750, 10, 600), \
(5, 1, 'Right Bar 1 of Desktop Search, 2 Column Paper View', 'E', 30, 200, 30, 300), \
(6, 1, 'Right Bar 2 of Desktop Search, 2 Column Paper View', 'E', 30, 200, 30, 1000), \
(7, 1, 'Roof of Desktop Search, 2 Column Paper View', 'E', 30, 1500, 10, 300), \
(8, 1, 'Basement of Desktop Search, 2 Column Paper View', 'E', 30, 1500, 10, 300), \
\
(1000, 2, 'Message Area 1 of Desktop Search, Newsline View', 'E', 30, 1500, 10, 500), \
(1001, 2, 'Right Bar 1 of Desktop Search, Newsline View', 'E', 30, 200, 30, 300), \
(1002, 2, 'Right Bar 2 of Desktop Search, Newsline View', 'E', 30, 200, 30, 1000), \
(1003, 2, 'Roof of Desktop Search, Newsline View', 'E', 30, 1500, 10, 300), \
(1004, 2, 'Basement of Desktop Search, Newsline View', 'E', 30, 1500, 10, 300), \
\
(2000, 3, 'Message 1 of Desktop Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
(2001, 3, 'Message 2 of Desktop Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
(2002, 3, 'Message Area 1 of Desktop Search, 1 Column Paper View', 'E', 30, 1500, 10, 600), \
(2003, 3, 'Right Bar 1 of Desktop Search, 1 Column Paper View', 'E', 30, 200, 30, 300), \
(2004, 3, 'Right Bar 2 of Desktop Search, 1 Column Paper View', 'E', 30, 200, 30, 1000), \
(2005, 3, 'Roof of Desktop Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
(2006, 3, 'Basement of Desktop Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
\
(3000, 4, 'Message 1 of Tab Search, 2 Column Paper View', 'E', 30, 750, 10, 300), \
(3001, 4, 'Message 2 of Tab Search, 2 Column Paper View', 'E', 30, 750, 10, 300), \
(3002, 4, 'Message Area 1 of Tab Search, 2 Column Paper View', 'E', 30, 750, 10, 600), \
(3003, 4, 'Message Area 2 of Tab Search, 2 Column Paper View', 'E', 30, 750, 10, 600), \
(3004, 4, 'Right Bar 1 of Tab Search, 2 Column Paper View', 'E', 30, 200, 30, 300), \
(3005, 4, 'Right Bar 2 of Tab Search, 2 Column Paper View', 'E', 30, 200, 30, 1000), \
(3006, 4, 'Roof of Tab Search, 2 Column Paper View', 'E', 30, 1500, 10, 300), \
(3007, 4, 'Basement of Tab Search, 2 Column Paper View', 'E', 30, 1500, 10, 300), \
\
(4000, 5, 'Message Area 1 of Tab Search, Newsline View', 'E', 30, 1500, 10, 500), \
(4001, 5, 'Right Bar 1 of Tab Search, Newsline View', 'E', 30, 200, 30, 300), \
(4002, 5, 'Right Bar 2 of Tab Search, Newsline View', 'E', 30, 200, 30, 1000), \
(4003, 5, 'Roof of Tab Search, Newsline View', 'E', 30, 1500, 10, 300), \
(4004, 5, 'Basement of Tab Search, Newsline View', 'E', 30, 1500, 10, 300), \
\
(5000, 6, 'Message 1 of Tab Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
(5001, 6, 'Message 2 of Tab Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
(5002, 6, 'Message Area 1 of Tab Search, 1 Column Paper View', 'E', 30, 1500, 10, 600), \
(5003, 6, 'Right Bar 1 of Tab Search, 1 Column Paper View', 'E', 30, 200, 30, 300), \
(5004, 6, 'Right Bar 2 of Tab Search, 1 Column Paper View', 'E', 30, 200, 30, 1000), \
(5005, 6, 'Roof of Tab Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
(5006, 6, 'Basement of Tab Search, 1 Column Paper View', 'E', 30, 1500, 10, 300), \
\
(6000, 7, 'Message Area 1 of Mobile Search, Newsline View', 'E', 30, 1000, 10, 500), \
(6001, 7, 'Roof of Mobile Search, Newsline View', 'E', 30, 1000, 10, 200), \
(6002, 7, 'Basement of Mobile Search, Newsline View', 'E', 30, 1000, 10, 200), \
\
(7000, 8, 'Message 1 of Mobile Search, 1 Column Paper View', 'E', 30, 1000, 10, 300), \
(7001, 8, 'Message 2 of Mobile Search, 1 Column Paper View', 'E', 30, 1000, 10, 300), \
(7002, 8, 'Message Area 1 of Mobile Search, 1 Column Paper View', 'E', 30, 1000, 30, 600), \
(7003, 8, 'Roof of Mobile Search, 1 Column Paper View', 'E', 30, 1000, 30, 300), \
(7004, 8, 'Basement of Mobile Search, 1 Column Paper View', 'E', 30, 1000, 30, 300), \
\
(8000, 9, 'Message Image of Desktop Message', 'E', 30, 1500, 10, 300), \
(8001, 9, 'Message Middle of Desktop Message', 'E', 30, 1500, 10, 300), \
(8002, 9, 'Message Bottom of Desktop Message', 'E', 30, 1500, 10, 600), \
(8003, 9, 'Right Bar 1 of Desktop Message', 'E', 30, 200, 30, 300), \
(8004, 9, 'Right Bar 2 of Desktop Message', 'E', 30, 200, 30, 1000), \
(8005, 9, 'Roof of Desktop Message', 'E', 30, 1500, 10, 300), \
(8006, 9, 'Basement of Desktop Message', 'E', 30, 1500, 10, 300), \
\
(9000, 10, 'Message Image of Tab Message', 'E', 30, 1500, 10, 300), \
(9001, 10, 'Message Middle of Tab Message', 'E', 30, 1500, 10, 300), \
(9002, 10, 'Message Bottom of Tab Message', 'E', 30, 1500, 10, 600), \
(9003, 10, 'Right Bar 1 of Tab Message', 'E', 30, 200, 30, 300), \
(9004, 10, 'Right Bar 2 of Tab Message', 'E', 30, 200, 30, 1000), \
(9005, 10, 'Roof of Tab Message', 'E', 30, 1500, 10, 300), \
(9006, 10, 'Basement of Tab Message', 'E', 30, 1500, 10, 300), \
\
(10000, 11, 'Message Image of Mobile Message', 'E', 30, 1000, 10, 300), \
(10001, 11, 'Message Middle of Mobile Message', 'E', 30, 1000, 10, 300), \
(10002, 11, 'Message Bottom of Mobile Message', 'E', 30, 1000, 10, 600), \
(10003, 11, 'Roof of Mobile Message', 'E', 30, 1000, 10, 300), \
(10004, 11, 'Basement of Mobile Message', 'E', 30, 1000, 10, 300) \
;" \
| ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdSize ..."
echo "create table if not exists AdSize ( \
      id INTEGER UNSIGNED NOT NULL PRIMARY KEY, \
      name CHAR(64) character set ascii NOT NULL UNIQUE KEY, \
      status ENUM ('E', 'D') NOT NULL, \
      width INTEGER UNSIGNED NOT NULL, \
      height INTEGER UNSIGNED NOT NULL,
      KEY(width, height)  \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Filling AdSize ..."

echo "insert ignore into AdSize \
(id, name, status, width, height) values \
(1, 'Leaderboard', 'E', 728, 90), \
(2, 'Banner', 'E', 468, 60), \
(3, 'Large Rectangle', 'E', 336, 280), \
(4, 'Netboard', 'E', 580, 400), \
(5, 'Medium Rectangle', 'E', 300, 250), \
(6, 'Wide Skyscraper', 'E', 160, 600), \
(7, 'Mobile Banner', 'E', 320, 50), \
(8, 'Half Banner', 'E', 234, 60), \
(9, 'Large Mobile Banner', 'E', 320, 100), \
(10, 'Large Leaderboard', 'E', 970, 90), \
(11, 'Skyscraper', 'E', 120, 600), \
(12, 'Vertical Banner', 'E', 120, 240), \
(13, 'Large Skyscraper', 'E', 300, 600), \
(14, 'Square', 'E', 250, 250), \
(15, 'Small Square', 'E', 200, 200), \
(16, 'Small Rectangle', 'E', 180, 150), \
(17, 'Button', 'E', 125, 125), \
(18, 'Vertical Rectangle', 'E', 240, 400), \
(19, 'Panorama', 'E', 980, 120), \
(20, 'Triple Widescreen', 'E', 250, 360), \
(21, 'Top Banner', 'E', 930, 180), \
(22, 'Horizontal Large', 'E', 728, 15), \
(23, 'Horizontal Medium', 'E', 468, 15), \
(24, 'Vertical X-Large', 'E', 200, 90), \
(25, 'Vertical Large', 'E', 180, 90), \
(26, 'Vertical Medium', 'E', 160, 90), \
(27, 'Vertical Small', 'E', 120, 90) \
;" \
| ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdCondition ..."
echo "create table if not exists AdCondition ( \
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      name VARCHAR(128) NOT NULL, \
      status ENUM ('E', 'D', 'L') NOT NULL, \
      rnd_mod TINYINT UNSIGNED NOT NULL, \
      rnd_mod_from TINYINT UNSIGNED NOT NULL, \
      rnd_mod_to TINYINT UNSIGNED NOT NULL, \
      group_freq_cap INTEGER UNSIGNED NOT NULL, \
      group_count_cap INTEGER UNSIGNED NOT NULL, \
      page_sources VARCHAR(40960) NOT NULL, \
      page_source_exclusions VARCHAR(40960) NOT NULL, \
      message_sources VARCHAR(40960) NOT NULL, \
      message_source_exclusions VARCHAR(40960) NOT NULL, \
      page_categories VARCHAR(4096) NOT NULL, \
      page_category_exclusions VARCHAR(4096) NOT NULL, \
      message_categories VARCHAR(4096) NOT NULL, \
      message_category_exclusions VARCHAR(4096) NOT NULL, \
      search_engines VARCHAR(256) character set ascii NOT NULL, \
      search_engine_exclusions VARCHAR(256) character set ascii NOT NULL, \
      crawlers VARCHAR(512) character set ascii NOT NULL, \
      crawler_exclusions VARCHAR(512) character set ascii NOT NULL, \
      languages VARCHAR(512) character set ascii NOT NULL, \
      language_exclusions VARCHAR(512) character set ascii NOT NULL, \
      countries VARCHAR(512) character set ascii NOT NULL, \
      country_exclusions VARCHAR(512) character set ascii NOT NULL, \
      ip_masks VARCHAR(102400) character set ascii NOT NULL, \
      ip_mask_exclusions VARCHAR(102400) character set ascii NOT NULL, \
      INDEX advertiser (advertiser), UNIQUE (advertiser, name) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table Ad ..."
echo "create table if not exists Ad ( \
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      name VARCHAR(128) NOT NULL, \
      status ENUM ('E', 'D', 'L') NOT NULL, \
      size INTEGER UNSIGNED NOT NULL REFERENCES AdSize ( id ), \
      text VARCHAR(10240) NOT NULL, \
      INDEX advertiser (advertiser), UNIQUE (advertiser, name) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdPageAdvRestriction ..."
echo "create table if not exists AdPageAdvRestriction ( \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      page INTEGER UNSIGNED NOT NULL REFERENCES AdPage ( id ), \
      max_ad_num INTEGER UNSIGNED NOT NULL, \
      PRIMARY KEY (advertiser, page) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdPageAdvAdvRestriction ..."
echo "create table if not exists AdPageAdvAdvRestriction ( \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      page INTEGER UNSIGNED NOT NULL REFERENCES AdPage ( id ), \
      advertiser2 BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      max_ad_num INTEGER UNSIGNED NOT NULL, \
      PRIMARY KEY (advertiser, page, advertiser2) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdCampaign ..."
echo "create table if not exists AdCampaign ( \
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      name VARCHAR(128) NOT NULL, \
      status ENUM ('E', 'D', 'L') NOT NULL, \
      INDEX advertiser (advertiser), UNIQUE (advertiser, name) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdGroup ..."
echo "create table if not exists AdGroup ( \
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      campaign BIGINT UNSIGNED NOT NULL REFERENCES AdCampaign ( id ), \
      name VARCHAR(128) NOT NULL, \
      status ENUM ('E', 'D', 'L') NOT NULL, \
      auction_factor DOUBLE NOT NULL, \
      INDEX campaign (campaign), UNIQUE (campaign, name) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdGroupCondition ..."
echo "create table if not exists AdGroupCondition ( \
      group_id BIGINT UNSIGNED NOT NULL REFERENCES AdGroup ( id ), \
      condition_id BIGINT UNSIGNED NOT NULL REFERENCES AdCondition ( id ), \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      PRIMARY KEY (group_id, condition_id) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdCampaignCondition ..."
echo "create table if not exists AdCampaignCondition ( \
      campaign_id BIGINT UNSIGNED NOT NULL REFERENCES AdCampaign ( id ), \
      condition_id BIGINT UNSIGNED NOT NULL REFERENCES AdCondition ( id ), \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      PRIMARY KEY (campaign_id, condition_id) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdPlacement ..."
echo "create table if not exists AdPlacement ( \
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, \
      advertiser BIGINT UNSIGNED NOT NULL REFERENCES Advertiser ( id ), \
      group_id BIGINT UNSIGNED NOT NULL REFERENCES AdGroup ( id ), \
      name VARCHAR(128) NOT NULL, \
      status ENUM ('E', 'D', 'L') NOT NULL, \
      slot BIGINT UNSIGNED NOT NULL REFERENCES AdSlot ( id ), \
      ad BIGINT UNSIGNED NOT NULL REFERENCES Ad ( id ), \
      cpm DOUBLE NOT NULL, \
      inject ENUM ('D', 'F') NOT NULL, \
      INDEX group_id (group_id), UNIQUE (group_id, name) \
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Creating table AdSelector ..."

echo "create table if not exists AdSelector ( \
      status ENUM ('E', 'D') NOT NULL, \
      update_num BIGINT UNSIGNED NOT NULL) \
      engine=InnoDB;" | \
ng-mysql --user root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi

echo_date "Filling table AdSelector ..."

echo "insert ignore into AdSelector set status='E', update_num=0;" \
| ng-mysql --user=root NewsGate

if test $? -eq 0; then echo_date "Done"; else echo_date "Failed"; exit 1; fi
