#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Removing EventBank.dict-hash cache file ..."

rm $3/Event/EventBank.dict-hash 2>/dev/null

# Resets possibly non-zero $?
echo "" > /dev/null
