#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Creating CategoryLocale table ..."

echo "create table CategoryLocale ( \
      category_id BIGINT UNSIGNED NOT NULL REFERENCES Category ( id ),
      lang SMALLINT UNSIGNED NOT NULL, \
      country SMALLINT UNSIGNED NOT NULL, \
      name VARCHAR(512) BINARY NOT NULL, \
      PRIMARY KEY (category_id, lang, country),
      INDEX category_id_index (category_id)
) engine=InnoDB;" | ng-mysql --user=root NewsGate

if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi
