#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Cleaning MessageBank service cache ..."

rm -r -f $3/Message/*

if test $? -eq 0; then
  echo "Done"
else
  echo "Failed"
  exit 1
fi
