#!/bin/sh

# product   : NewsGate - news search WEB server
# copyright : Copyright (c) 2005-2016 Karen Arutyunov
# licenses  : CC BY-NC-SA 3.0; see accompanying LICENSE file
#             Commercial; contact karen.arutyunov@gmail.com

echo "Cleaning Event table ..."

echo "truncate Event;" | ng-mysql --user root NewsGate
if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo "Cleaning EventMessage table ..."

echo "truncate EventMessage;" | ng-mysql --user root NewsGate
if test $? -eq 0; then echo "Done"; else echo "Failed"; exit 1; fi

echo "Cleaning EventBank service cache ..."

rm -r -f $3/Event/*

if test $? -eq 0; then
  echo "Done"
else
  echo "Failed"
  exit 1
fi
